#pragma once
void FillRand(int arr[], const int n, int minRand = 0, int maxRand = 100);
void FillRand(char arr[], const int n, int minRand = 0, int maxRand = 100);
void FillRand(double arr[], const int n, int minRand = 0, int maxRand = 100);
void FillRand(int** arr, const int rows, const int cols, int minRand = 0, int maxRand = 100);
void FillRand(char** arr, const int rows, const int cols, int minRand = 0, int maxRand = 256);
void FillRand(double** arr, const int rows, const int cols, int minRand = 0, int maxRand = 100);
template<typename T>void Print(T arr[], const int n);
template<typename T>void Print(T** arr, const int rows, const int cols);
template<typename T>void OddEven(T arr[], const int n, int even[], int odd[]);
template<typename T>T* PushFront(T arr[], int& n, int& value);
template<typename T>void Push_Row_Front(T**& arr, int& rows, const int cols);
template<typename T>T* PushBack(T arr[], int& n, T value);
template<typename T> void Push_Row_Back(T**& arr, int& rows, const int cols);
template<typename T>T* insert(T arr[], int& n, int value, int  it);
template<typename T> void insert_row(T**& arr, int& rows, const int cols, int it);
template<typename T> void insert_col(T** arr, const int rows, int& cols, int it);
template<typename T>T* pop_back(T arr[], int& n);
template<typename T> void Pop_Row_Back(T**& arr, int& rows, const int cols);
template<typename T>T* pop_front(T arr[], int& n);
template<typename T>void Pop_Row_Front(T**& arr, int& rows, const int cols);
template<typename T>T* erase(T arr[], int& n, int  it);
template<typename T>void erase_row(T**& arr, int& rows, const int cols, int it);
template<typename T>void erase_col(T** arr, const int rows, int& cols, int it);
template<typename T>void clear(T** arr, const int rows);
template<typename T>T** allocate(int const rows, int const cols);
template<typename T>void Push_Col_Back(T** arr, const int rows, int& cols);
template<typename T>void Pop_Col_Back(T** arr, const int rows, int& cols);
template<typename T>void Pop_Col_Front(T** arr, const int rows, int& cols);
template<typename T>void Push_Col_Front(T** arr, const int rows, int& cols);
